### ISSUE TITLE
Diarization ends in crash

### ISSUE THREAD

**Issue by styler2go** [yinruiqing/pyannote-whisper#14]
Command used: `python -m pyannote_whisper.cli.transcribe C:\Users\style\Desktop\sicherheit\1045400524.wav --model tiny --diarization True`

```
Traceback (most recent call last):
  File "C:\Users\style\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\style\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\style\PycharmProjects\pyannote-whisper\pyannote_whisper\cli\transcribe.py", line 131, in <module>
    cli()
  File "C:\Users\style\PycharmProjects\pyannote-whisper\pyannote_whisper\cli\transcribe.py", line 126, in cli
    res = diarize_text(result, diarization_result)
  File "C:\Users\style\PycharmProjects\pyannote-whisper\pyannote_whisper\utils.py", line 59, in diarize_text
    res_processed = merge_sentence(spk_text)
  File "C:\Users\style\PycharmProjects\pyannote-whisper\pyannote_whisper\utils.py", line 43, in merge_sentence
    elif text[-1] in PUNC_SENT_END:
IndexError: string index out of range
```

Any idea why this is happening? I have this for multiple files, but not for all files.

**Comment by manubatet** [comment]
I am having the same problem, did you fix it?

When parsing the segments, there is some kind of delay and at the end of the loop it tries to access the audio in a position later than the last one

**Comment by yinruiqing** [comment]
Please give me an example to reproduce this problem.

**Comment by styler2go** [comment]
So, i've played around a bit more and i noticed it is only happening in my modified main.py so i will close this issue.

But if someone could help me finding the issue? I am pretty mich just doing:
```python
import whisper
import sys
import codecs
import ffmpeg
from pyannote.audio import Pipeline
from pyannote_whisper.utils import diarize_text

pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
                                    use_auth_token="abc")
model = whisper.load_model("medium")

oriFile = sys.argv[1]
wavFile = oriFile + ".wav"
txtFile = oriFile + ".txt"

(
    ffmpeg
    .input(oriFile)
    .output(wavFile)
    .run()
)

asr_result = model.transcribe(wavFile)
diarization_result = pipeline(wavFile)
final_result = diarize_text(asr_result, diarization_result)
```

and after that some  post-processing. The error i get comes at the last line though:
```
Traceback (most recent call last):
  File "C:\Users\style\PycharmProjects\pyannote-whisper\main.py", line 25, in <module>
    final_result = diarize_text(asr_result, diarization_result)
  File "C:\Users\style\PycharmProjects\pyannote-whisper\pyannote_whisper\utils.py", line 64, in diarize_text
    res_processed = merge_sentence(spk_text)
  File "C:\Users\style\PycharmProjects\pyannote-whisper\pyannote_whisper\utils.py", line 48, in merge_sentence
    elif text[-1] in PUNC_SENT_END:
IndexError: string index out of range
```
I've been logging the results of the loop inside `def merge_sentence(spk_text):` 
![image](https://user-images.githubusercontent.com/2152144/232557036-a715287a-e10c-4d53-8729-897ae8204eb0.png)

and the results of this is:
```
text => ''
spk => None
seg = []
```
