### ISSUE TITLE
Syntax error on model_name

### ISSUE THREAD

**Issue by CRad14** [yinruiqing/pyannote-whisper#6]
I think this is a really cool project and am trying to get it working unfortunately I keep getting this error

python -m pyannote_whisper.cli.transcribe ~/Downloads/preamble10.wav --model medium --diarization True
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/conrad/Documents/pyannote-whisper-main/pyannote_whisper/cli/transcribe.py", line 67
    model_name: str = args.pop("model")
              ^
SyntaxError: invalid syntax

Any thoughts?

**Comment by yinruiqing** [comment]
Whisper used Python 3.9.9. Please check your python version.
